var annotated_dup =
[
    [ "FormAdditionalSettings", "class_form_additional_settings.html", "class_form_additional_settings" ],
    [ "FormPlotInterface", "class_form_plot_interface.html", "class_form_plot_interface" ],
    [ "fromSettingConnect", "classfrom_setting_connect.html", "classfrom_setting_connect" ],
    [ "MainWindow", "class_main_window.html", "class_main_window" ],
    [ "QT_END_NAMESPACE", "class_q_t___e_n_d___n_a_m_e_s_p_a_c_e.html", null ],
    [ "TANSWER_STATUS", "struct_t_a_n_s_w_e_r___s_t_a_t_u_s.html", "struct_t_a_n_s_w_e_r___s_t_a_t_u_s" ],
    [ "TCommonFunction", "class_t_common_function.html", "class_t_common_function" ],
    [ "TComPort", "class_t_com_port.html", "class_t_com_port" ],
    [ "TComSettings", "struct_t_com_settings.html", "struct_t_com_settings" ],
    [ "TProtocolAdditionalSettings", "struct_t_protocol_additional_settings.html", "struct_t_protocol_additional_settings" ],
    [ "TProtocolLinearCoef", "struct_t_protocol_linear_coef.html", "struct_t_protocol_linear_coef" ],
    [ "TProtocolPacketAdditionalSettings", "struct_t_protocol_packet_additional_settings.html", "struct_t_protocol_packet_additional_settings" ],
    [ "TProtocolPacketCommandReal", "struct_t_protocol_packet_command_real.html", "struct_t_protocol_packet_command_real" ],
    [ "TProtocolPacketPing", "struct_t_protocol_packet_ping.html", "struct_t_protocol_packet_ping" ],
    [ "TProtocolPacketSettings", "struct_t_protocol_packet_settings.html", "struct_t_protocol_packet_settings" ],
    [ "TProtocolPacketStatusAnswer", "struct_t_protocol_packet_status_answer.html", "struct_t_protocol_packet_status_answer" ],
    [ "TProtocolPacketTelemetry", "struct_t_protocol_packet_telemetry.html", "struct_t_protocol_packet_telemetry" ],
    [ "TProtocolPacketTerminal", "struct_t_protocol_packet_terminal.html", "struct_t_protocol_packet_terminal" ],
    [ "TProtocolPidCoef", "struct_t_protocol_pid_coef.html", "struct_t_protocol_pid_coef" ],
    [ "TProtocolSettingControl", "struct_t_protocol_setting_control.html", "struct_t_protocol_setting_control" ],
    [ "TProtocolSettingsWheel", "struct_t_protocol_settings_wheel.html", "struct_t_protocol_settings_wheel" ],
    [ "TProtocolSettingsWithoutRegulator", "struct_t_protocol_settings_without_regulator.html", "struct_t_protocol_settings_without_regulator" ],
    [ "TProtocolSettingsWithRegulator", "struct_t_protocol_settings_with_regulator.html", "struct_t_protocol_settings_with_regulator" ],
    [ "TProtocolTelemetryAnswerData", "struct_t_protocol_telemetry_answer_data.html", "struct_t_protocol_telemetry_answer_data" ],
    [ "TSCALING_FACTORS", "struct_t_s_c_a_l_i_n_g___f_a_c_t_o_r_s.html", "struct_t_s_c_a_l_i_n_g___f_a_c_t_o_r_s" ],
    [ "TTelemetryValuesDisplay", "struct_t_telemetry_values_display.html", "struct_t_telemetry_values_display" ],
    [ "TTYPE_PACKET", "struct_t_t_y_p_e___p_a_c_k_e_t.html", "struct_t_t_y_p_e___p_a_c_k_e_t" ]
];