var dir_81f4ff6295e7cd30f5566b903fec8079 =
[
    [ "debug", "dir_9beb1c6a55fbac09d7f30ab4b6c9aabb.html", "dir_9beb1c6a55fbac09d7f30ab4b6c9aabb" ],
    [ "release", "dir_b2f9f8706af9a3ae26c9742837caf9fa.html", "dir_b2f9f8706af9a3ae26c9742837caf9fa" ],
    [ "crc16.cpp", "crc16_8cpp.html", "crc16_8cpp" ],
    [ "crc16.h", "crc16_8h.html", "crc16_8h" ],
    [ "defines.h", "defines_8h.html", "defines_8h" ],
    [ "formadditionalsettings.cpp", "formadditionalsettings_8cpp.html", null ],
    [ "formadditionalsettings.h", "formadditionalsettings_8h.html", "formadditionalsettings_8h" ],
    [ "formplotinterface.cpp", "formplotinterface_8cpp.html", "formplotinterface_8cpp" ],
    [ "formplotinterface.h", "formplotinterface_8h.html", "formplotinterface_8h" ],
    [ "fromsettingconnect.cpp", "fromsettingconnect_8cpp.html", null ],
    [ "fromsettingconnect.h", "fromsettingconnect_8h.html", "fromsettingconnect_8h" ],
    [ "main.cpp", "main_8cpp.html", "main_8cpp" ],
    [ "mainwindow.cpp", "mainwindow_8cpp.html", "mainwindow_8cpp" ],
    [ "mainwindow.h", "mainwindow_8h.html", "mainwindow_8h" ],
    [ "Protocol.c", "_protocol_8c.html", "_protocol_8c" ],
    [ "Protocol.h", "_protocol_8h.html", "_protocol_8h" ],
    [ "qcustomplot.cpp", "qcustomplot_8cpp.html", null ],
    [ "qcustomplot.h", "qcustomplot_8h.html", "qcustomplot_8h" ],
    [ "tcommonfunction.cpp", "tcommonfunction_8cpp.html", "tcommonfunction_8cpp" ],
    [ "tcommonfunction.h", "tcommonfunction_8h.html", "tcommonfunction_8h" ],
    [ "tcomport.cpp", "tcomport_8cpp.html", null ],
    [ "tcomport.h", "tcomport_8h.html", "tcomport_8h" ]
];